### ISSUE TITLE
ingo error

### ISSUE THREAD

**Issue by mars-1** [schachmat/ingo#1]
Hello, in  jessie/sid (ubuntu) :

go get -u github.com/schachmat/ingo
# github.com/schachmat/ingo

go/src/github.com/schachmat/ingo/in.go:92:20: error: reference to undefined identifier ‘flag.UnquoteUsage’
   _, usage := flag.UnquoteUsage(f)
                    ^

**Comment by schachmat** [comment]
You need go >=1.5 which is not in jessie (yet?). You can use goenv or install it manually.
