### ISSUE TITLE
undefined while installation

### ISSUE THREAD

**Issue by jhaeusle** [schachmat/ingo#2]
When installing the module, it throws an error:

`$ go get -u github.com/schachmat/ingo`
`# github.com/schachmat/ingo`
`./in.go:92: undefined: flag.UnquoteUsage` 

Unfortunately I'm not into go at all, I just wanted to use the wego weather forecast.
It works great on my mac with osx 10.11 but on centos7 it doesn't install because of the above error.

Please bear with me if this a OSI-Layer-8 ;)

If you need further information about my environment, feel free to ask.

**Comment by jhaeusle** [comment]
Hi,

Just saw the closed issue which was solved by pointing out that go >1.5 is needed. 
I have 1.4.2 here on my centos, so I guess I have to update that first.

Probably it would be a good idea to implement a check into the tool to clearify that while compiling.

Sorry for the hassle, I'll close the issue now.

Best Regards,

Jan Haeusle

**Comment by schachmat** [comment]
I don't know about a sane way to do compile time checks in go. You can install go 1.5 or later via pygoenv or manually from the golang website as noted in the README.
