### ISSUE TITLE
undefined: flag.UnquoteUsage

### ISSUE THREAD

**Issue by erikw** [schachmat/ingo#4]
I get the following error when installing:

```bash
$ go get -u github.com/schachmat/ingo
# github.com/schachmat/ingo
src/godeps/src/github.com/schachmat/ingo/in.go:134: undefined: flag.UnquoteUsage
```

How can I come around this? :)

**Comment by schachmat** [comment]
Heyho @erikw,

#1, #2 or the readme should help you out. :)

**Comment by erikw** [comment]
Ha true! I had an older go version overlayed in my PATH :P.
